# Site settings
author: Yakura Marzett
title: Yakura's Coding Blog
header-img: img/home-bg.png
email: marzettyakura@yahoo.com
copyright_name: Yakura Marzett
description: > # this means to ignore newlines until "baseurl:"
  Follow me on my coding journey!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  marzettyakura

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
